name: Android

env:
  CONAN_REPOSITORY: https://conan.rgpaul.com
  CONAN_REPOSITORY_NAME: rgpaul
  CONAN_PACKAGE_NAME: curl
  CONAN_USERNAME: rgpaul
  CONAN_CHANNEL: stable

on: 
  push:
    branches:
      - master
      - develop

jobs:

  armv7-Release:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OS_NAME: linux
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-android.sh armv7 19 Release
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh
      if: github.ref == 'refs/heads/master' # only deploy a master build

  armv7-Debug:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OS_NAME: linux
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-android.sh armv7 19 Debug
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh
      if: github.ref == 'refs/heads/master' # only deploy a master build

  armv8-Release:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OS_NAME: linux
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-android.sh armv8 21 Release
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh
      if: github.ref == 'refs/heads/master' # only deploy a master build

  armv8-Debug:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OS_NAME: linux
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-android.sh armv8 21 Debug
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh
      if: github.ref == 'refs/heads/master' # only deploy a master build

  x86-Release:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OS_NAME: linux
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-android.sh x86 19 Release
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh
      if: github.ref == 'refs/heads/master' # only deploy a master build

  x86-Debug:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OS_NAME: linux
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-android.sh x86 19 Debug
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh
      if: github.ref == 'refs/heads/master' # only deploy a master build

  x86_64-Release:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OS_NAME: linux
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-android.sh x86_64 21 Release
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh
      if: github.ref == 'refs/heads/master' # only deploy a master build

  x86_64-Debug:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OS_NAME: linux
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-android.sh x86_64 21 Debug
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh
      if: github.ref == 'refs/heads/master' # only deploy a master build
