name: Linux

env:
  CONAN_REPOSITORY: https://conan.rgpaul.com
  CONAN_REPOSITORY_NAME: rgpaul
  CONAN_PACKAGE_NAME: curl
  CONAN_USERNAME: rgpaul
  CONAN_CHANNEL: stable

on:
  create:
    ref_type: tag

jobs:
  
  x86_64-Release:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OS_NAME: linux
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(echo ${GITHUB_REF:10})
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: list dependencies for github cache key
      run: |
        source ${HOME}/.profile
        conan info . -bo ALL > dependencies-info.txt
        cat dependencies-info.txt
    - name: Cache conan data
      uses: actions/cache@v1
      with:
        path: ${HOME}/.conan/data
        key: ${{ runner.OS }}-conan-linux-x86_64-release-${{ hashFiles('dependencies-info.txt') }}
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-linux.sh x86_64 Release
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh

  x86_64-Debug:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OS_NAME: linux
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(echo ${GITHUB_REF:10})
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: list dependencies for github cache key
      run: |
        source ${HOME}/.profile
        conan info . -bo ALL > dependencies-info.txt
        cat dependencies-info.txt
    - name: Cache conan data
      uses: actions/cache@v1
      with:
        path: ${HOME}/.conan/data
        key: ${{ runner.OS }}-conan-linux-x86_64-debug-${{ hashFiles('dependencies-info.txt') }}
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-linux.sh x86_64 Debug
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh
