name: macOS

env:
  CONAN_REPOSITORY: https://conan.rgpaul.com
  CONAN_REPOSITORY_NAME: rgpaul
  CONAN_PACKAGE_NAME: curl
  CONAN_USERNAME: rgpaul
  CONAN_CHANNEL: stable

on: 
  push:
    branches:
      - master
      - develop

jobs:
  
  x86_64-Release:
    runs-on: macos-latest
    env:
      GITHUB_OS_NAME: macos
      DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-macos.sh x86_64 Release
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh
      if: github.ref == 'refs/heads/master' # only deploy a master build

  x86_64-Debug:
    runs-on: macos-latest
    env:
      GITHUB_OS_NAME: macos
      DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-macos.sh x86_64 Debug
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh
      if: github.ref == 'refs/heads/master' # only deploy a master build
