name: Windows

env:
  CONAN_REPOSITORY: https://conan.rgpaul.com
  CONAN_REPOSITORY_NAME: rgpaul
  CONAN_PACKAGE_NAME: curl
  CONAN_USERNAME: rgpaul
  CONAN_CHANNEL: stable

on: 
  push:
    branches:
      - master
      - develop

jobs:

  x86_64-Release:
    runs-on: windows-latest
    env:
      GITHUB_OS_NAME: windows
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
      shell: bash
    - name: install and setup conan
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-setup.ps1
      shell: powershell
    - name: create conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\build-windows.ps1 -ARCH x86_64 -BUILD_TYPE Release
      shell: powershell
    - name: deploy conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-deploy.ps1
      shell: powershell
      if: github.ref == 'refs/heads/master' # only deploy a master build

  x86_64-Debug:
    runs-on: windows-latest
    env:
      GITHUB_OS_NAME: windows
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
      shell: bash
    - name: install and setup conan
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-setup.ps1
      shell: powershell
    - name: create conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\build-windows.ps1 -ARCH x86_64 -BUILD_TYPE Debug
      shell: powershell
    - name: deploy conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-deploy.ps1
      shell: powershell
      if: github.ref == 'refs/heads/master' # only deploy a master build

  x86-Release:
    runs-on: windows-latest
    env:
      GITHUB_OS_NAME: windows
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
      shell: bash
    - name: install and setup conan
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-setup.ps1
      shell: powershell
    - name: create conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\build-windows.ps1 -ARCH x86 -BUILD_TYPE Release
      shell: powershell
    - name: deploy conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-deploy.ps1
      shell: powershell
      if: github.ref == 'refs/heads/master' # only deploy a master build

  x86-Debug:
    runs-on: windows-latest
    env:
      GITHUB_OS_NAME: windows
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
      shell: bash
    - name: install and setup conan
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-setup.ps1
      shell: powershell
    - name: create conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\build-windows.ps1 -ARCH x86 -BUILD_TYPE Debug
      shell: powershell
    - name: deploy conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-deploy.ps1
      shell: powershell
      if: github.ref == 'refs/heads/master' # only deploy a master build
